export const ADD_TICKET = "ADD_TICKET";
export const LOAD_TICKETS = "LOAD_TICKETS";
export const UPDATE_TICKET_STATUS = "UPDATE_TICKET_STATUS";

export const ADD_TASK = "ADD_TASK";
export const UPDATE_TASK_NAME = "UPDATE_TASK_NAME";
export const TOGGLE_TASK_STATUS = "TOGGLE_TASK_STATUS";
export const DELETE_TASK = "DELETE_TASK";

export const LOAD_MENU_ITEMS = "LOAD_MENU_ITEMS";